name: build-and-test
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  unit-tests-linux-x86_64:
    name: Linux x86_64 (build & test)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOSC_ENABLE_SANITIZERS=ON
          make cosc-static
          make cosc-shared
          make unit_tests
          ctest --output-on-failure
  unit-tests-android-arm64:
    name: Android arm64-v8a (build only)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
          make cosc-static
          make cosc-shared
          make unit_tests
  unit-tests-windows:
    name: Windows (build only)
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --config Debug --parallel --target cosc-static
          cmake --build build --config Debug --parallel --target cosc-shared
          cmake --build build --config Debug --parallel --target unit_tests
          cmake --build build --config Debug --target RUN_TESTS --parallel
  build-emscripten:
    name: Emscripten (build only)
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.41
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p build
          cd build
          emcmake cmake .. -DCMAKE_BUILD_TYPE=Debug
          emmake make cosc-static
          emmake make cosc-shared
