name: build-and-test
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  unit-tests-linux-x86_64:
    name: Linux arm64-v8a
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCOSC_ENABLE_SANITIZERS=ON
          cmake --build build --config Debug --parallel --target unit_tests
          cmake test
  unit-tests-android-arm64:
    name: Android arm64-v8a
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
          cmake --build build --config Debug --parallel --target unit_tests
          cmake test
  unit-tests-windows:
    name: Linux arm64-v8a
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --config Debug --parallel --target unit_tests
          cmake test
  build-emscripten:
    name: Emscripten
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.41
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          emcmake cmake -B build -DCMAKE_BUILD_TYPE=Debug
          emcmake cmake --build build --config Debug --parallel --target cosc-static
          emcmake cmake --build build --config Debug --parallel --target cosc-shared
