name: build-and-test
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  unit-tests-linux-x86_64:
    name: Linux x86_64 (build & test)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCOSC_ENABLE_SANITIZERS=ON
      - name: Build static
        run: |
          cmake --build build --config Debug --target cosc-static
      - name: Build shared
        run: |
          cmake --build build --config Debug --target cosc-shared
      - name: Build examples.
        run: |
          cmake --build build --config Debug --target examples
      - name: Build unit tests
        run: |
          cmake --build build --config Debug --target unit_tests
      - name: Run unit tests
        run: |
          cd build
          env CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
  unit-tests-android-arm64:
    name: Android arm64-v8a (build only)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
      - name: Build static
        run: |
          cmake --build build --config Debug --target cosc-static
      - name: Build shared
        run: |
          cmake --build build --config Debug --target cosc-shared
      - name: Build examples.
        run: |
          cmake --build build --config Debug --target examples
      - name: Build unit tests
        run: |
          cmake --build build --config Debug --target unit_tests
  unit-tests-windows:
    name: Windows (build only)
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug
      - name: Build static
        run: |
          cmake --build build --config Debug --target cosc-static
      - name: Build shared
        run: |
          cmake --build build --config Debug --target cosc-shared
      - name: Build examples
        run: |
          cmake --build build --config Debug --target examples
      - name: Build unit tests
        run: |
          cmake --build build --config Debug --parallel --target unit_tests
  build-emscripten:
    name: Emscripten (build only)
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.41
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: |
          emcmake cmake -B build -DCMAKE_BUILD_TYPE=Debug
      - name: Build static
        run: |
          emcmake cmake --build build --config Debug --target cosc-static
      - name: Build shared
        run: |
          emcmake cmake --build build --config Debug --target cosc-shared
